name: Build and release sidecar

on:
  push:
    tags:
      - 'v*-*'

jobs:
  build:
    name: Build sidecar
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build MacOS app
        if: matrix.os == 'macos-latest'
        run: |
          make mac

      - name: Upload MacOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: sidecar-release-${{ github.ref_name }}-${{ runner.os }}-amd64
          path: build/*

      - name: Build linux app
        if: matrix.os == 'ubuntu-latest'
        run: |
          make linux

      - name: Upload linux artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: sidecar-release-${{ github.ref_name }}-${{ runner.os }}-amd64
          path: build/*

      - name: Build linux armv7 app
        if: matrix.os == 'ubuntu-latest'
        run: |
          make linux_armv7

      - name: Upload linux_armv7 artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: sidecar-release-${{ github.ref_name }}-${{ runner.os }}-armv7
          path: build/*

      - name: Build Windows app
        if: matrix.os == 'ubuntu-latest'
        run: |
          make windows

      - name: Upload Windows artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: sidecar-release-${{ github.ref_name }}-windows-amd64
          path: build/*

  release:
    name: Release sidecar
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7

      - name: Tar artifacts
        run: |
          for dir in $(ls)
          do
              tar -czpf $dir.tar.gz $dir
          done
          ls -al

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.tar.gz"
          generate_release_notes: true
