name: Build and release sidecar
on:
  push:
    branches:
      - master
#on:
#  push:
#    tags:
#      - 'v*-*'

jobs:
  build:
    name: Build and release sidecar
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build linux app
      if: matrix.os == 'ubuntu-latest'
      run: |
        make build

    - name: Build windows app
      if: matrix.os == 'windows-latest'
      run: |
        go build main.go
        dir

    - run: |
      mkdir -p path/to/artifact
    
    - run: |
      echo hello > path/to/artifact/world.txt
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

    - run: |
      ls path/to/artifact
