name: Run sidecar test
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run sidecar test
    env:
      SERVER: ${{secrets.server}}
      COMPLEXPATH: ${{secrets.complexpath}}
      CUSTOMHEADERNAME: ${{secrets.customheadername}}
      CUSTOMHEADERVALUE: ${{secrets.customheadervalue}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
  
      - name: Download module
        run: go mod download
  
      - name: Write conf.toml
        run: |
          cd cmd/sidecar-server
          cat << EOF > conf.toml
          ProxyPort = 4396
          Server = "$SERVER"
          ComplexPath = "$COMPLEXPATH"
          GfwListUrl = "https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"
          [CustomHeaders]
          $CUSTOMHEADERNAME = "$CUSTOMHEADERVALUE"
          EOF
  
      - name: Run Server
        run: |
          cd cmd/sidecar-server
          go build -o sidecar-server main.go
          ./sidecar-server start -daemon
  
      - name: Trust Cert
        run: |
          sudo cp cmd/sidecar-server/sidecar.crt /usr/local/share/ca-certificates/sidecar.crt
          sudo update-ca-certificates
  
      - name: Check process info
        run: |
          # sleep 30s wait for server up
          sleep 30
          cat cmd/sidecar-server/server.log
          sudo netstat -nutlp
  
      - name: Send Test request
        run: |
          curl -v -I -x 127.0.0.1:4396 https://www.google.com
